window.$ = window.jQuery = require('jquery');
import 'jquery.nicescroll';
import 'slick-carousel';

import './components/main-header/main-header';
import './components/menu-toggle/menu-toggle';
import './components/applicant/applicant';
import './components/interview/interview';
import './components/filters/filters';
import './components/reg-form/reg-form';
import './components/search-form/search-form';
import './components/salary-filter/salary-filter';
import './components/dropdown/dropdown';
import './components/star/star';
import './components/worksheet-form/worksheet-form';
import './components/candidates-settings/candidates-settings';
import './components/vacancy/vacancy';
import './components/subscribes/subscribes';
import './components/my-interview/my-interview';
import './components/message-form/message-form';
